name: Atlas 3.0 CI

on:
  pull_request:
    branches:
      - main
      - epic/*

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false

    env:
      VITE_IGNORE_MSW: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'

      - name: Install dependencies
        run: yarn

      - name: Run Vitest
        run: yarn vitest